services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - net-mern
    environment:
      MONGO_URI: mongo://mongo:27017/mydatabase  
    depends_on:
      - mongo
    
  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"  
    networks:
      - net-mern
    environment:
      REACT_APP_API_URL: http://backend:5050 

  mongo:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - net-mern
    volumes:
      - mongo-data:/data/db  

networks:
  net-mern:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

